apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo-dev
  template:
    metadata:
      labels:
        app: kargo-demo-dev
    spec:
      containers:
      - name: app
        image: nomrajdevops/kargo-demo:v1
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: kargo-demo-dev
  namespace: dev
spec:
  selector:
    app: kargo-demo-dev
  ports:
  - port: 80
    targetPort: 3000

        
        
