apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo-prod
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kargo-demo-prod
  template:
    metadata:
      labels:
        app: kargo-demo-prod
    spec:
      containers:
      - name: app
        image: nomrajdevops/kargo-demo:v1
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: kargo-demo-prod
  namespace: prod
spec:
  selector:
    app: kargo-demo-prod
  ports:
  - port: 80
    targetPort: 3000
